version: '3.8'

services:
  apache:
    build: ./apache
    ports:
      - "8080:80"
    container_name: handler_confusion_apache
    depends_on:
      - modsec
    volumes:
      - ./apache/mime.types:/etc/apache2/mime.types:ro
      - ./apache/custom.conf:/etc/apache2/conf-enabled/custom.conf:ro
      - ./apache/phpinfo.php:/var/www/html/phpinfo.php:ro

  modsec:
    build: ./modsecurity
    container_name: modsecurity
