version: '3.8'

services:
  apache:
    build: .
    ports:
      - "8080:80"
    container_name: handler_confusion
    volumes:
      - ./mime.types:/etc/apache2/mime.types:ro
      - ./custom.conf:/etc/apache2/conf-enabled/custom.conf:ro
      - ./phpinfo.php:/var/www/html/phpinfo.php:ro
